name: CI
on:
  pull_request:
    paths-ignore:
      - "documents/**"
      - "**.md"
  push:
    paths-ignore:
      - "documents/**"
      - "**.md"
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------
  x86_64-linux-gnu-uwvm-default:
    name: x86_64-linux-gnu (ubuntu-24.04) uwvm
    runs-on: ubuntu-24.04 # noble
    strategy:
      matrix:
        mode: ["debug"]
        policies:
          [
            "build.sanitizer.address,build.sanitizer.leak,build.sanitizer.undefined",
          ]
        cxx_flags: [
            "", # SSE2
            "-msse3", # SSE2 SSE3
            "-mssse3", # SSE2 SSE3 SSSE3
            "-msse4 -mbmi -mbmi2", # SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 BMI BMI2
            "-mavx -mbmi -mbmi2 -mprfchw", # SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX BMI BMI2
            "-mavx2 -mbmi -mbmi2 -mprfchw" # SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 BMI BMI2
            # "-mavx512bw -mbmi -mbmi2 -mprfchw", # SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512BW BMI BMI2
            # "-mavx512vbmi -mavx512vbmi2 -mbmi -mbmi2 -mprfchw" # SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512BW AVX512VBMI AVX512VBMI2 BMI BMI2
            # "-mavx10.2 -mbmi -mbmi2 -mprfchw"
            # "-mapxf -mavx10.2 -mbmi -mbmi2 -mprfchw"
          ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          sudo apt-get install clang-22 clang-tools-22 lld-22 xmake

      - name: Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-22 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="${{ matrix.cxx_flags }}" --test-libfuzzer=y
      - name: Build
        run: xmake b -rv
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -v

  # ---------------------------------------------------------------------------
  x86_64-linux-gnu-uwvm-cxxmodule:
    if: ${{ !always() }}
    name: x86_64-linux-gnu (ubuntu-24.04) uwvm (cxx-module build)
    runs-on: ubuntu-24.04 # noble
    strategy:
      matrix:
        mode: ["debug"]
        policies:
          [
            "build.sanitizer.address,build.sanitizer.leak,build.sanitizer.undefined",
          ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          sudo apt-get install clang-22 clang-tools-22 lld-22 xmake

      - name: Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-22 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --use-cxx-module=y
      - name: Build
        run: xmake b -rv
      - name: Check UWVM version
        run: xmake run uwvm --version

  # ---------------------------------------------------------------------------
  x86_64-windows-gnu:
    name: x86_64-windows-gnu (MINGW ${{ matrix.env.name }})
    runs-on: windows-latest
    strategy:
      matrix:
        env:
          - name: "CLANG64"
            prefix: mingw-w64-clang-x86_64
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
        min-win: [
          "WIN10",   # NT 10.x (Win10/Win11/WS16/WS19/WS22/WS25)
          "WINBLUE", # NT 6.3 (Win8.1/WS12R2)
          "WIN8",    # NT 6.2 (Win8/WS12)
          "WIN7",    # NT 6.1 (Win7/WS08R2)
          "VISTA",   # NT 6.0 (Vista/WS08)
          "WINXP64", # NT 5.2 (WS03/WinXP x64)
          "WINXP",   # NT 5.1 (WinXP)
          "WIN2K",   # NT 5.0 (Win2000/WS2K)
          "NT400",   # NT 4.0 (unverified)
          "NT351",   # NT 3.51 (unverified)
          "NT350",   # NT 3.50 (unverified)
          "NT310",   # NT 3.10 (closest to NT 3.0, unverified)
          "WINME",   # Win9x 4.90
          "WIN98",   # Win9x 4.10
          "WIN95"    # Win9x 4.00
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.env.name }}
          update: true
          install: |
            ${{ matrix.env.prefix }}-cc
            ${{ matrix.env.prefix }}-xmake
      - name: Configure
        run: xmake f -p mingw --use-llvm=y -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --mingw-min=${{ matrix.min-win }}
      - name: Build
        run: xmake b -rv
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -v

  # ---------------------------------------------------------------------------
  x86_64-freebsd14:
    if: ${{ !always() }}
    name: x86_64-freebsd14
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    steps:
      - uses: actions/checkout@v4
      - uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          version: "14.2"
      - name: Setup
        run: |
          clang -v
          which clang-22
          which lld-22
          which xmake
      - name: Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/local/lib/llvm-22 -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
      - name: Build
        run: xmake b -rv
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -v
